version: "3"
services:
  udagramd-db:
    image: localhost:5050/postgres
    container_name: udagramd-db
    networks:
      - udagram
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_DB: $POSTGRES_DB

  backend-user:
    image: localhost:5050/udagram-api-user:latest
    container_name: backend-user
    networks:
      - udagram
    depends_on:
      - udagramd-db
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL

  backend-feed:
    image: localhost:5050/udagram-api-feed:latest
    container_name: backend-feed
    networks:
      - udagram
    depends_on:
      - udagramd-db
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL

  reverseproxy:
    image: localhost:5050/reverseproxy:latest
    container_name: reverseproxy
    networks:
      - udagram
    ports:
      - "8081:8080"
    depends_on:
      - udagramd-db
      - backend-user
      - backend-feed

  front-end:
    image: localhost:5050/udagram-frontend
    ports:
      - "8100:80"

networks:
  udagram:
